### PR TITLE
242: Sidebar collapse.

### PR DESCRIPTION
**Pull request by oxmap**
Added sidebar collapse related to issue #242 .

### CODE REVIEW

**Comment by webnegar** [comment]
Sidebar collapse does not work on RTL mode entirely.

**Comment by oxmap** [comment]
@webnegar, can you send additional information for your issue. And I’ll modify.

**Comment by webnegar** [comment]
when sidebar collapse in RTL mode, there is white space between main panel and right sidebar.

gap-rtl

thank you.

**Comment by webnegar** [comment]
Also in LTR mode:
gap-ltr

**Comment by webnegar** [comment]
> @webnegar, can you send additional information for your issue. And I’ll modify.

thank you aout your help, 
this changes can solve the sidebar problem in RTL mode in layout.component.scss: 

`* {
    -webkit-transition: margin-right 0.2s ease-in-out;
    -moz-transition: margin-right 0.2s ease-in-out;
    -ms-transition: margin-right 0.2s ease-in-out;
    -o-transition: margin-right 0.2s ease-in-out;
    transition: margin-right 0.2s ease-in-out;
}

.main-container {
    margin-top: 56px;
    margin-right: 235px;
    padding: 15px;
    -ms-overflow-x: hidden;
    overflow-x: hidden;
    overflow-y: scroll;
    position: relative;
    overflow: hidden;
}

.collapsed {
    margin-right: 50px;
}
@media screen and (max-width: 992px) {
    .main-container {
        margin-right: 0px !important;
    }
}

@media print {
    .main-container {
        margin-top: 0px !important;
        margin-right: 0px !important;
    }
}
`
but how to write css style that supports RTL or LTR together?

**Pull request merged**
